youtube/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from django.conf import settings

from . import views

app_name='youtube'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^submit/$',views.submit,name='submit'),
    url(r'^neo/(?P<neo_data>[0-9A-Za-z_-]+)/$',views.neo,name='neo'),
    url(r'^watch/(?P<video_id>[0-9A-Za-z_-]+)/$', views.watch,name='watch' ),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^checklogin/$',views.checklogin,name='checklogin'),
    url(r'^thanks/$',views.thanks,name='thanks'),
    url(r'^history/$',views.history,name='history'),
    url(r'$',views.index,name='index'),
]

youtube/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

youtube/forms.py
from django import forms

class initialSearch(forms.Form):
   search_key_text = forms.CharField(max_length = 100)
   #password = forms.CharField(widget = forms.PasswordInput())
class userLogin(forms.Form):
	username = forms.CharField(max_length = 100)
	password = forms.CharField(max_length=100)


class userRegistration(forms.Form):
	first_name=forms.CharField(max_length=100)
	last_name=forms.CharField(max_length=100)
	# email=forms.EmailField()
	# email=forms.EmailField()
	# sex=forms.CharField(max_length=10)
	# age=forms.IntField()
	# password=forms.CharField(max_length=100)

youtube/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,render_to_response
from django import forms
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from youtube.forms import initialSearch,userLogin,userRegistration
import sys
sys.path.insert(0, '/home/sunil/Documents/assignment/gui/youtube/databaseCreate')
import didyoumean
import mongoSearch
import neoSearch
import json
import handler
import sql_checklogin
# import didyoumean
#session_running=False


def index(request):

    if '0' in request.session:
    	output=handler.history(request.session['0'])
    else:
    	output=handler.nonHistory()
    #print output
    finalOutput={}
    for video_id in output:
    	#print video_id[0]
    	individual_output=mongoSearch.searchIndividual(video_id[0])
    	#print individual_output
    	for i in individual_output:
    		finalOutput[video_id[0]]=i
    username='login'
    if '0' in request.session:
    	username=request.session['0']
    context={"flag":username,"message":finalOutput}


    #print finalOutput

    return render(request,'youtube/index.html',context)
def logout(request):
	if '0' in request.session:
		del request.session['0']
		request.session.modified=True
	return render(request,'youtube/logout.html',{})
	# return HttpResponseRedirect("youtube/index.html/")
def submit(request):
	context={}
	username='login'
	if request.method == "GET":
		data=request.GET.get('search_key_text','')
		correctedSuggestion=didyoumean.didyoumeanResult(data)
		flag=0
		if correctedSuggestion != data:
			flag=1
			data=correctedSuggestion
		if '0' in request.session:
			username=request.session['0']
		if data:
			context={"message":data}
			neo_data=data
			mongoSearch.search(context,username)
			searchedOutput=mongoSearch.sorted_output
			if flag==1:
				context={"username":username,"flag":correctedSuggestion,"message":searchedOutput}
			else:
				context={"username":username,"message":searchedOutput}
			length=len(searchedOutput)
			return render(request,'youtube/submit.html',context)
	return render(request,'youtube/submit.html',{})
def login(request):
	# pass
	#print "i am vishal"
	return render(request,'youtube/login.html',{})


def watch(request,video_id):
	neoSearchOutput=neoSearch.search_on_click(video_id)
	relatedVideo={}
	username='login'
	for obj in neoSearchOutput:
		for data in obj:
			singleOutput=mongoSearch.searchIndividual(obj[data]['id'])
			for ii in singleOutput:
				relatedVideo[obj[data]['id']]=ii
	current_video_info=mongoSearch.searchIndividual(video_id)
	current_detail={}
	for obj in current_video_info:
		current_detail=obj
	if '0' in request.session:
		username=request.session['0']
		handler.add_history(request.session['0'],video_id)
		handler.non_signed_history(video_id)
	else:
		handler.non_signed_history(video_id)
	output={"message":relatedVideo,"current_detail":current_detail,"username":username}
	print mongoSearch.increase_view_count(video_id)
	return render(request,'youtube/watch.html',output)

def neo(request,neo_data):
	print 'neodata'
	data=request.GET.get('')
	#print neo_data
	return render(request,'youtube/neo.html',{'message':neo_data})
def checklogin(request):
	# request.session[0]=''
	form=userLogin(request.POST)
	if request.method=='POST':
		#form.save()
		if form.is_valid():
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			#print username,password
			# userExistingStatus=sql(username,password)
			status=sql_checklogin.checkLogin(username,password)
			# request.session['user_id']=username
			# print 'status',type(status)
			# print 'session',request.session['0']
			if status!=0:
				request.session[0]=username
				session_running=True
			#print request.session['0']
	return render(request,'youtube/status.html',{})

def thanks(request):
	form=userRegistration(request.POST)
	if request.method=='POST':
		if form.is_valid():
			first_name=form.cleaned_data['first_name']
			last_name=form.cleaned_data['last_name']
			#password=form.cleaned_data['password']
			#email=form.cleaned_data['email']
			#age=form.cleaned_data['age']
			#sex=form.cleaned_data['sex']
			status=handler.user_registration([first_name,last_name,'sex','age','vishal_email','password'])
			if status:
				message='thanks for registration'
				return render(request,'youtube/thanks.html',{"message":message})
			#print first_name,last_name
			message='Already registered.Please login to continue.'
			return render(request,'youtube/thanks.html',{"message":message})



def history(request):
	username=''
	if '0' in request.session:
		output=handler.history(request.session['0'])
		finalOutput={}
		for video_id in output:
			individual_output=mongoSearch.searchIndividual(video_id[0])
			for i in individual_output:
				finalOutput[video_id[0]]=i
		username=request.session['0']
	context={"user_id":username,"message":finalOutput}
	return render(request,'youtube/history.html',context)
	#return render(request,'youtube/history',{})
    	# output=handler.history(request.session['0'])
	    # #print output
	    # finalOutput={}
	    # for video_id in output:
	    # 	#print video_id[0]
	    # 	individual_output=mongoSearch.searchIndividual(video_id[0])
	    # 	#print individual_output
	    # 	for i in individual_output:
	    # 		finalOutput[video_id[0]]=i
	    # username='login'
	    # if '0' in request.session:
	    # 	username=request.session['0']
	    # context={"flag":username,"message":finalOutput}

youtube/templates/youtube/history.html
<!DOCTYPE html>
<html>
<head>
	<title>History</title>
	{% load static %}
    <link rel="shortcut icon" type="image/png" href="{%static 'youtube/img/search-icon.png'%}"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My Tube</title>
    {% load static %}
    <link rel="stylesheet" href="footer-distributed-with-contact-form.css">
    <link rel="stylesheet" type="text/css" href=" {%static 'youtube/assets/css/main.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'youtube/css/mystyle.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'youtube/css/simple-sidebar.css'%}">
    <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->


    <!-- Bootstrap Core CSS -->
    <link href="{%static 'youtube/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{%static 'youtube/css/portfolio-item.css'%}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="container-fluid" style="  border-bottom: 2px solid #00b386;">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 <img class="rotating" src="{%static 'youtube/img/iitlogo.png'%}"
                        style="position:absolute; margin-left:0px; margin-top:3px;
                        width:40px; height:40px;">
                <a class="navbar-brand" href="{%url 'youtube:index' %}" style="float:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My Tube</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
 <!--                <div class="">

  -->

            <form  method="GET" action="/submit/" style="height: 12px;" >
              {% csrf_token %}
            <input type="text"  name="search_key_text" size="85" placeholder="search videos" id = "tags" required="required" style="margin-left:75px; margin-top:7px; font-size: 17px; font-family: Helvetica Neue,Helvetica,Arial,sans-serif; font-color:red; height: 35px; ">
                    <!-- <input type="submit" value="search" style="font-size: 13pt; margin:left:-20px;">
                     -->    <input type="image" src="{%static 'youtube/img/search-icon.png'%}" alt="Submit" width="28" height="28"
                        style="position:absolute; margin-left:-30px; margin-top:6px;">
            </form>
<!--
                </div>
 -->                <ul class="nav navbar-nav " style=" float:right;">
                    <li>
                        <a href="./upload.html">Upload</a>
                    </li>
                    <li>
                        <a href="#">Notification</a>
                    </li>
                    <li id="login"  >
                        <a href="{% url 'youtube:login' %}">{{user_id}}</a>
                    </li>
               </ul>
       <!--      </div>
        -->  <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

	<div class="container" >
    <font color="red"><strong>your history <br><br> </strong></font>
	 <div id="under" >
	{% if user_id %}
    {% for key,value in message.items|slice:"20" %}

    <a href="{% url 'youtube:watch' value.videoInfo.id %}">
    <div class="col-sm-3 col-xs-3" id="cool2">
        <div class="wrapper">
            <img src="{{value.videoInfo.snippet.thumbnails.default.url}}" class="hover thumb" />
        </div>
     <strong>{{value.videoInfo.snippet.description|slice:":50"}}<br>
     Channel: </strong>{{value.videoInfo.snippet.channelTitle}}

    </div>
    </a>

    {% endfor %}
	{% endif %}
    </div>
    <!-- {% if not user_id %}
        please login
    {% endif %} -->
</div>

</script>

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</script>
</body>
</html>

youtube/templates/youtube/logout.html
<!DOCTYPE html>
<html>
<title>Logout SUcessfully</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<body background="https://s-media-cache-ak0.pinimg.com/originals/02/9f/cc/029fcc2433166e932786ceaf281e1181.jpg">
<div class="container-fluid" style="margin-left:0% ;margin-top:15% ;text-align:center">
<font size=7>Log out sucessfully</font>
<br>
<a href=" {% url 'youtube:login' %} ">login </a> or
<a href=" {% url 'youtube:index' %} ">Watch more.</a>
</div>

</body>
</html>

youtube/templates/youtube/neo.html
hi
{{ message }}

youtube/templates/youtube/status.html
<!DOCTYPE html>
<html>
<title>Logout SUcessfully</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<body background="https://s-media-cache-ak0.pinimg.com/originals/02/9f/cc/029fcc2433166e932786ceaf281e1181.jpg">
<div class="container-fluid" style="margin-left:0% ;margin-top:15% ;text-align:center">
<font size=7>Logged in sucessfully</font>
<br>
<!-- <a href=" {% url 'youtube:login' %} ">login </a> or -->
<a href="{% url 'youtube:index' %}"> watch here</a>
</div>

</body>
</html>

youtube/templates/youtube/submit.html
<!-- {% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="icon" href="https://i.ytimg.com/vi/omp7cFYtE1I/hqdefault.jpg" type="image/jpg" >
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Gaurav Sunil Shivam vishal">

    <title>My Tube</title>
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'youtube/css/mystyle.css' %} ">
    <link  rel="stylesheet" type="text/css" href="{% static 'youtube/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'youtube/css/portfolio-item.css' %}"  >
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid" style="  border-bottom: 2px solid #00b386;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% load static %}
                 <a href="http://www.iitg.ernet.in" target="_blank" ><img  title="IIT Guwahati" class="rotating" src="{% static 'youtube/img/iitlogo.png' %}"
                        style="position:absolute; margin-left:-10px; margin-top:3px;
                        width:40px; height:40px;" alt="logo">
                  </a>
                <a href="{% url 'youtube:index'%} " class="navbar-brand" href="" style="float:left;" title="My Tube Home" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My Tube</a>
            </div>
            <form  method="GET" action="/submit/">
              {% csrf_token %}
              <input name="search_key_text" type="text" size="85" placeholder="search videos.." style="margin-left:95px; margin-top:7px; font-size: 17px; font-family: Helvetica Neue,Helvetica,Arial,sans-serif; font-color:red;" required >
       		  {%load static%}
     		   <input type="image" src="{%static 'youtube/img/search-icon.png'%}" alt="Submit" width="28" height="28"
  					    style="position:absolute; margin-left:-30px; margin-top:8px;">
  			</form>
               <ul class="nav navbar-nav " style=" float:right; margin-top:-40px;  " >
                    <li>
                        <a href="#">Upload</a>
                    </li>
                    <li>
                        <a href="#">Notification</a>
                    </li>
                    <li id="login"  >
                        <a href="{% url 'youtube:login'%} ">Login</a>
                    </li>
               </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">


        </div>
        <div class="row" >

            <div class="col-lg-12">
                <h3 class="page-header">Related Videos</h3>
            </div>
            {% if message %}
				{% for i in message|slice:"20"  %}

            <div class="col-lg-12"  >
					<div class="col-sm-4 col-xs-4">
		                 <a href="{% url 'youtube:watch' i.0.0.videoInfo.id %}">
		                    <img class="img-responsive portfolio-item" src="{{i.0.0.videoInfo.snippet.thumbnails.default.url}}" alt="" width="30%" height="30%" >
		                </a>
	            	</div>
	            	<div class="col-sm-8 col-xs-8" style=""  >
		                <a href="{% url 'youtube:watch' i.0.0.videoInfo.id %}">
		                 <h4 class="img-responsive portfolio-item" alt="" width="30%" height="30%"  >{{i.0.0.videoInfo.snippet.title}} </h4>
		                 <p>{{i.0.0.videoInfo.snippet.channelTitle}}  </p>
		                 <p>{{i.0.0.videoInfo.statistics.viewCount}} Views</p>
		                 <p>{{i.0.0.videoInfo.snippet.description|slice:":100"}}...</p>
		                </a>
	            	</div>

	        </div>
	       <hr>
				{% endfor %}
			{% endif %}
			{% if not message %}
				<h2 style="color:red; text-align: center;">-----   sorry, no result found  ------</h2>

			{% endif %}
        </div>
        <hr>
        <footer style=" position:fixed; bottom:0;">
            <div class="row">
                <div class="col-lg-12">
                </div>
            </div>
        </footer>

    </div>
    {%load static%}
    <script src="{%static 'youtube/js/jquery.js'%}"></script>
    <script src="{%static 'youtube/js/bootstrap.min.js'%}"></script>

</body>

</html>

{% endblock %} -->




<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="shortcut icon" type="image/png" href="{%static 'youtube/img/search-icon.png'%}"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My Tube</title>
    <link rel="stylesheet" type="text/css" href="{%static 'youtube/css/mystyle.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'youtube/css/simple-sidebar.css'%}">

    <link href="{%static 'youtube/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{%static 'youtube/css/portfolio-item.css'%}" rel="stylesheet">
</head>

<body>

    <!-- Navigation -->
            <div id="wrapper" style="position:absolute; margin-top:-17px;">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#" ">
                        Menu
                    </a>

                </li>
                                <hr style="border-color:red; position:relative; margin-top:0px;">

                <li>
                    <a href="#">Bookmarks</a>
                </li>
                <li>
                    <a href="#">History</a>
                </li>
                <li>
                    <a href="#">Subscriptions</a>
                </li>
                <li>
                    <a href="#">Channels</a>
                </li>
                <li>
                    <a href="#">Trending</a>
                </li>
                <li>
                    <a href="#">Watch Later</a>
                </li>
                <li>
                    <a href="#">Log-out</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
<a href="#menu-toggle" class="btn btn-default" id="menu-toggle" style="background-color:#a7adba; width:1px;border:none; outline:0;  min-height: 100%; position:fixed; z-index:999 ;text-align: center; border-right:1px solid black; box-shadow: 5px 5px 5px #888888;" ></a>


    </div>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="container-fluid" style="  border-bottom: 2px solid #00b386;">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 <img class="rotating" src="{%static 'youtube/img/iitlogo.png'%}"
                        style="position:absolute; margin-left:-0px; margin-top:3px;
                        width:40px; height:40px;">
                <a class="navbar-brand" href=" {% url 'youtube:index' %}" style="float:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My Tube</a>
            </div>

        <form  method="GET" action="/submit/" style="height: 12px;" >
              {% csrf_token %}
            <input type="text" name="search_key_text" size="85" placeholder="search videos.." required="required" style="margin-left:75px; margin-top:7px; font-size: 17px; font-family: Helvetica Neue,Helvetica,Arial,sans-serif; font-color:red; height: 35px; ">
                    <!-- <input type="submit" value="search" style="font-size: 13pt; margin:left:-20px;">
                     -->    <input type="image" src="{%static 'youtube/img/search-icon.png'%}" alt="Submit" width="28" height="28"
                        style="position:absolute; margin-left:-30px; margin-top:6px;">
        </form>
        <ul class="nav navbar-nav " style=" float:right;" style="padding-top: -100px;" >
                    <li>
                        <a href="./upload.html">Upload</a>
                    </li>
                    <li>
                        <a href="#">Notification</a>
                    </li>
                    <li id="login"  >
                        <a href="{% url 'youtube:login' %}">{{username}}</a>
                    </li>
               </ul>
       <!--      </div>
        -->  <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Portfolio Item Heading -->
        <div class="row" >
            <div class="col-lg-12">
                <h1 class="page-header text-center ">Searched Videos
                </h1>
            </div>
        </div>

    {% if  flag %}
        <h3 style="color:red; text-align: center;">did you mean: {{flag}}</h3>

    {% endif %}

    {% if message %}
        {% for i in message|slice:"20"  %}
            <br>
        <a href=' {% url 'youtube:watch' i.0.0.videoInfo.id %} ' style="text-decoration: none; ">
        <div class="container row" style="margin-left:100px;  border:1px solid #A9A9A9; height:230px; width:950px;">

        <div class="col-lg-3" style="padding:0px; height:200px; ">
        <img src="{{i.0.0.videoInfo.snippet.thumbnails.default.url}}" style="height:90%; width:100%; margin-top:10px;" >
        </div>
        <div class="col-lg-9">
            <u><h4>{{i.0.0.videoInfo.snippet.title|slice:":50"}}</h4></u>
            <font  color="black">
            <p>{{i.0.0.videoInfo.snippet.description|slice:":100"}}...</p>
            <strong>channelId :</strong> {{i.0.0.videoInfo.snippet.channelId}}...<br>
            <strong>publishedAt : </strong>{{i.0.0.videoInfo.snippet.publishedAt}}<br>
            <strong>liveBroadcastContent :</strong> {{i.0.0.videoInfo.snippet.liveBroadcastContent}}<br>
            <strong>channelTitle : </strong>{{i.0.0.videoInfo.snippet.channelTitle}}<br>

        <div class="row" >
        <div class="col-xs-2">
        <img src="{%static 'youtube/img/like.png'%}"><p>{{i.0.0.videoInfo.statistics.likeCount}}</p>
        </div>
        <div class="col-xs-2">
        <img src="{%static 'youtube/img/dislike.png'%}"><p>{{i.0.0.videoInfo.statistics.dislikeCount}}</p>
        </div>
        <div class="col-xs-2">
        <img src="{%static 'youtube/img/view.png'%}"><p>{{i.0.0.videoInfo.statistics.viewCount}}</p>
        </div>
            </div>
        </font>


        </div>

        </font-color>
        </div>
        </a>


        {% endfor %}
    {% endif %}
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'youtube/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'youtube/js/bootstrap.min.js' %} "></script>
     <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

youtube/templates/youtube/thanks.html
{{message}}